import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";

export const BossBattlesTracks: Track[] = [
  {
    title: "Abaddon",
    title_id: "abaddon",
    source: "/musics/abaddon.mp3",
    duration: 419,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Battle Droid",
    title_id: "battle-droid",
    source: "/musics/battle-droid.mp3",
    duration: 213,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Behemoth",
    title_id: "behemoth",
    source: "/musics/behemoth.mp3",
    duration: 245,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Belial",
    title_id: "belial",
    source: "/musics/belial.mp3",
    duration: 122,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Boss Challenge",
    title_id: "boss-challenge",
    source: "/musics/boss-challenge.mp3",
    duration: 195,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Brute",
    title_id: "brute",
    source: "/musics/brute.mp3",
    duration: 128,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Corrupter",
    title_id: "corrupter",
    source: "/musics/corrupter.mp3",
    duration: 131,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Democrawler (Instrumental)",
    title_id: "democrawler-instrumental",
    source: "/musics/democrawler-instrumental.mp3",
    duration: 316,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Democrawler",
    title_id: "democrawler",
    source: "/musics/democrawler.mp3",
    duration: 398,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Demogorgon",
    title_id: "demogorgon",
    source: "/musics/demogorgon.mp3",
    duration: 251,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Elder Naytiba",
    title_id: "elder-naytiba",
    source: "/musics/elder-naytiba.mp3",
    duration: 320,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Gigas",
    title_id: "gigas",
    source: "/musics/gigas.mp3",
    duration: 460,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Juggernaut",
    title_id: "juggernaut",
    source: "/musics/juggernaut.mp3",
    duration: 314,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Kaya",
    title_id: "kaya",
    source: "/musics/kaya.mp3",
    duration: 152,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Maelstrom",
    title_id: "maelstrom",
    source: "/musics/maelstrom.mp3",
    duration: 395,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Mann Phase 1",
    title_id: "mann-phase-1",
    source: "/musics/mann-phase-1.mp3",
    duration: 205,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Mann Phase 2",
    title_id: "mann-phase-2",
    source: "/musics/mann-phase-2.mp3",
    duration: 211,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Master Core",
    title_id: "master-core",
    source: "/musics/master-core.mp3",
    duration: 183,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Providence Final Phase 2",
    title_id: "providence-final-phase-2",
    source: "/musics/providence-final-phase-2.mp3",
    duration: 138,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Providence Final Phase",
    title_id: "providence-final-phase",
    source: "/musics/providence-final-phase.mp3",
    duration: 155,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Providence",
    title_id: "providence",
    source: "/musics/providence.mp3",
    duration: 612,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Raven",
    title_id: "raven",
    source: "/musics/raven.mp3",
    duration: 289,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Roxanne",
    title_id: "roxanne",
    source: "/musics/roxanne.mp3",
    duration: 212,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Royal Guard Quiel",
    title_id: "royal-guard-quiel",
    source: "/musics/royal-guard-quiel.mp3",
    duration: 215,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Scarlet Phase 1",
    title_id: "scarlet-phase-1",
    source: "/musics/scarlet-phase-1.mp3",
    duration: 184,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Scarlet Phase 2 (Instrumental)",
    title_id: "scarlet-phase-2-instrumental",
    source: "/musics/scarlet-phase-2-instrumental.mp3",
    duration: 225,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Scarlet Phase 2",
    title_id: "scarlet-phase-2",
    source: "/musics/scarlet-phase-2.mp3",
    duration: 224,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Stalker",
    title_id: "stalker",
    source: "/musics/stalker.mp3",
    duration: 345,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Su",
    title_id: "su",
    source: "/musics/su.mp3",
    duration: 99,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Tachy Boss Fight",
    title_id: "tachy-boss-fight",
    source: "/musics/tachy-boss-fight.mp3",
    duration: 650,
    created_at: new Date("2024-04-26"),
  },
  {
    title: "Unidentified Naytiba",
    title_id: "unidentified-naytiba",
    source: "/musics/unidentified-naytiba.mp3",
    duration: 272,
    created_at: new Date("2024-04-26"),
  }
].map((track) => ({
  ...track,
  ...Artists["stellar-blade"],
  ...Albums["boss-battles"],
}));
